[package]
name = "zero-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zero-core = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
blake3 = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
hmac = { workspace = true }
md-5 = { workspace = true }
sha1 = { workspace = true }
hkdf = { workspace = true }
aes = { workspace = true }
cipher = { workspace = true }
aes-gcm = { workspace = true }
chacha20poly1305 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
boringtun = { workspace = true }
ctr = { workspace = true }
x25519-dalek = { workspace = true }
ml-kem = { workspace = true }
base64 = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "io-util", "net", "time", "test-util"] }
