[package]
name = "zero-security"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zero-core = { workspace = true }
zero-evasion = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
webpki-roots = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }
x25519-dalek = { workspace = true }
ml-kem = { workspace = true }
ml-dsa = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
aes-gcm = { workspace = true }
subtle = { workspace = true }
chacha20poly1305 = "0.10"
ed25519-dalek = "2"
rand = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
zstd = { workspace = true }
zeroize = { workspace = true }
